version: "3.7"
services:
  mongo:
    image: mongo:4.2
    container_name: QLSV_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
     
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/backup:/data/backup